const programs=[
{id:'zirkus',name:'Zirkustheater',type:'kunst',grades:[2],day:'MO',time:'15:00–16:50',start:'21.09.2026',end:'21.06.2027',place:'Turnsaal',cost:'kostenlos',contact:'Anmeldung über die Klassenlehrkraft.',summary:'Zirkus- und Theaterangebot für die 2. Klasse.',source:'Schulische Angebotsübersicht',status:'ok'},
{id:'italiano-a',name:'Italienisch – Anfänger',type:'sprache',grades:[2,3,4],day:'MO',time:'15:00–15:50',start:'21.09.2026',end:'21.06.2027',place:'Nicht angegeben',cost:'kostenlos',contact:'Anmeldung über die Klassenlehrkraft.',summary:'Italienisch für Anfängerinnen und Anfänger der 2.–4. Klasse.',source:'Schulische Angebotsübersicht',status:'ok'},
{id:'italiano-f',name:'Italienisch – Fortgeschrittene',type:'sprache',grades:[2,3,4],day:'MO',time:'16:00–16:50',start:'21.09.2026',end:'21.06.2027',place:'Nicht angegeben',cost:'kostenlos',contact:'Anmeldung über die Klassenlehrkraft.',summary:'Italienisch für Fortgeschrittene der 2.–4. Klasse.',source:'Schulische Angebotsübersicht',status:'ok'},
{id:'football-girls',name:'Football School – Mädchen',type:'sport',grades:[1,2,3,4],day:'MO',time:'Tabelle: 17:00–17:50 · Plakat: 17:00–18:00',start:'05.10.2026',end:'Wintersemester-Terminliste am Plakat',place:'Turnsaal',cost:'Tabelle: 169 € / 12 Termine',contact:'https://www.footballschool.at · +43 676 3239024 · office@footballschool.at',summary:'Fußballkurs für Mädchen der 1.–4. Klasse.',source:'Schulische Tabelle + Football-School-Plakat',status:'warn',note:'Das gedruckte Plakat nennt Montag 17:00–18:00 und Kursstart 05.10.2026. Die Tabelle nennt 17:00–17:50 und 169 € / 12 Termine. Eine handschriftliche Notiz zu 169 € und Geschwisterrabatt wird nur als Zusatzhinweis behandelt.'},
{id:'football-boys',name:'Football School – Jungen',type:'sport',grades:[1,2,3,4],day:'DI',time:'Tabelle: 17:00–17:50 · Plakat: 17:00–18:00',start:'29.09.2026',end:'Wintersemester-Terminliste am Plakat',place:'Turnsaal',cost:'Tabelle: 169 € / 12 Termine',contact:'https://www.footballschool.at · +43 676 3239024 · office@footballschool.at',summary:'Fußballkurs für Jungen der 1.–4. Klasse.',source:'Schulische Tabelle + Football-School-Plakat',status:'warn',note:'Das gedruckte Plakat nennt Dienstag 17:00–18:00 und Kursstart 29.09.2026. Die Tabelle nennt 17:00–17:50. Die beiden Startdaten sind keine Alternativen: 05.10. gilt für Mädchen, 29.09. für Jungen.'},
{id:'singschule-di',name:'Singschule Wien – Dienstag',type:'musik',grades:[2,3,4],day:'DI',time:'13:00–15:50, je nach Gruppe',start:'Kein gesondertes Startdatum angegeben',end:'Schuljahr 2026/27',place:'3. Stock · Top 31 / Top 38',cost:'Keine Kosten angegeben',contact:'0699 12460260 · persönliche Anmeldung: 18.09.2026, 17:00–18:30, Top 38',summary:'Klavier und Wiener Kinderstimmen für die 2.–4. Klasse.',source:'Infoblatt der Singschule Wien',status:'ok',note:'Dienstag: 13:00–13:50 Klavier; 14:00–14:50 Singen für die 2. Klasse; 15:00–15:50 Singen für die 3.–4. Klasse. Laut Infoblatt richten sich Klavier, Musikkunde und Stimmbildung an die 2., 3. und 4. Klasse.'},
{id:'schach',name:'Schach',type:'strategie',grades:[1,2,3,4],day:'MI',time:'Tabelle: 15:00–15:50 · Folder: 13:00–15:50',start:'07.10.2026',end:'26.05.2027',place:'Top 30',cost:'119 € / Semester · 219 € / Schuljahr',contact:'https://www.schachkurse.at/anmeldung · schachkurse@spids.at',summary:'Schulschach für die 1.–4. Klasse mit Online-Voranmeldung.',source:'Schulische Tabelle + Schulschach-Folder',status:'warn',note:'Der Folder nennt ein Kursfenster von 13:00–15:50, die Tabelle 15:00–15:50. Die konkrete Kinderzeit wird daher als bestätigungspflichtig behandelt. Anmeldeschluss laut Folder: 03.10.2026.'},
{id:'tennis',name:'Tennis',type:'sport',grades:[1,2,3,4],day:'MI',time:'17:00–17:50',start:'Oktober 2026 – genauer Tag nicht angegeben',end:'01.05.2027 laut Tabelle',place:'Turnsaal',cost:'125 € / mind. 12 Termine · 230 € / mind. 24 Termine',contact:'https://www.tennis4everyone.at · office@tennis4everyone.at',summary:'Tennisangebot für die 1.–4. Klasse.',source:'Schulische Angebotsübersicht',status:'warn',note:'Im Startfeld steht nur „Oktober 26“, ohne konkreten Tag. Das Enddatum 01.05.2027 stammt aus der Tabelle.'},
{id:'kunst-1',name:'Kreativer Kunst Klub – 1. Klasse',type:'kunst',grades:[1],day:'MI',time:'15:00–15:50',start:'30.09.2026',end:'Quelldatum muss bestätigt werden',place:'Top 33',cost:'50 € / Monat inkl. Material',contact:'potteryclubvienna@gmail.com',summary:'Kreativer Kunst Klub speziell für die 1. Klasse.',source:'Schulische Angebotsübersicht',status:'warn',note:'Die Tabelle nennt als Enddatum 01.05.2026, also ein Datum vor dem Start am 30.09.2026. Das tatsächliche Enddatum muss der Anbieter bestätigen.'},
{id:'kunst-all',name:'Kreativer Kunst Klub – 1.–4. Klasse',type:'kunst',grades:[1,2,3,4],day:'MI',time:'16:00–17:30',start:'30.09.2026',end:'Quelldatum muss bestätigt werden',place:'Top 33',cost:'60 € / Monat inkl. Material',contact:'potteryclubvienna@gmail.com',summary:'Längeres kreatives Kunstangebot für die 1.–4. Klasse.',source:'Schulische Angebotsübersicht',status:'warn',note:'Auch in dieser Zeile steht 01.05.2026 als Enddatum und damit ein Datum vor dem Start.'},
{id:'motopaed',name:'Motopädagogik',type:'entwicklung',grades:[1,2,3,4],day:'DO',time:'17:00–17:50',start:'Nicht angegeben',end:'Nicht angegeben',place:'Turnsaal',cost:'Nicht angegeben',contact:'Verein AKMÖ · katharina.loy@hotmail.com',summary:'Bewegungsorientiertes, psychomotorisches Angebot für die 1.–4. Klasse.',source:'Schulische Angebotsübersicht',status:'warn',note:'Die Quelle enthält weder Beginn/Ende noch Kosten.'},
{id:'singschule-do',name:'Singschule Wien – Donnerstag',type:'musik',grades:[2,3,4],day:'DO',time:'12:00–16:50, je nach Gruppe',start:'Kein gesondertes Startdatum angegeben',end:'Schuljahr 2026/27',place:'3. Stock · Top 31 / Top 38',cost:'Keine Kosten angegeben',contact:'0699 12460260 · persönliche Anmeldung: 18.09.2026, 17:00–18:30, Top 38',summary:'Klavier, Musikkunde und Stimmbildung für die 2.–4. Klasse.',source:'Infoblatt der Singschule Wien',status:'ok',note:'Donnerstag: 12:00–12:50 Klavier; 13:00–13:50, 14:00–14:50 und 15:00–15:50 Musikkunde / Stimmbildung; 16:00–16:50 Klavier. Die Kleingruppen werden nach Absprache eingeteilt.'},
{id:'piano-wagner',name:'Klavier – Negar Wagner',type:'musik',grades:[1,2,3,4],day:'DO',time:'Einzeltermin zwischen 12:00 und 17:00',start:'Tabelle: 25.09.2025',end:'Tabelle: 01.06.2026',place:'Top 11',cost:'24 € / 25 Minuten Einzelunterricht',contact:'negar.wagner@gmail.com',summary:'25-minütiger Klavier-Einzelunterricht für die 1.–4. Klasse.',source:'Schulische Angebotsübersicht',status:'warn',note:'Die Daten verweisen auf das Schuljahr 2025/26, obwohl die Datei als Übersicht 2026/27 übermittelt wurde. Eine aktuelle Bestätigung ist erforderlich.'}
];
const dayNames={MO:'Montag',DI:'Dienstag',MI:'Mittwoch',DO:'Donnerstag'},typeNames={sport:'Sport',musik:'Musik',kunst:'Kunst',sprache:'Sprache',entwicklung:'Förderung',strategie:'Strategie'};
function linkify(text){const m=text.match(/https?:\/\/[^ ·]+/);if(!m)return text;return `<a href="${m[0]}" target="_blank" rel="noopener">Anmeldeseite</a><br>${text.replace(m[0],'').replace(/^ · /,'')}`}
function card(p){const grades=p.grades.length===1?`${p.grades[0]}. Klasse`:`${p.grades[0]}.–${p.grades.at(-1)}. Klasse`;return `<article class="card"><div class="card-head"><div><h3>${p.name}</h3><p class="summary">${p.summary}</p></div><span class="badge ${p.status==='warn'?'warn':''}">${p.status==='warn'?'Zu prüfen':'Laut Quelle'}</span></div><div class="chips"><span class="chip">${grades}</span><span class="chip">${dayNames[p.day]}</span><span class="chip">${p.time}</span><span class="chip">${typeNames[p.type]}</span></div><details class="details"><summary>Details</summary><ul class="kv"><li><span class="k">Zeit</span><span>${dayNames[p.day]} · ${p.time}</span></li><li><span class="k">Beginn</span><span>${p.start}</span></li><li><span class="k">Ende</span><span>${p.end}</span></li><li><span class="k">Ort</span><span>${p.place}</span></li><li><span class="k">Kosten</span><span>${p.cost}</span></li><li><span class="k">Anmeldung</span><span>${linkify(p.contact)}</span></li></ul>${p.note?`<div class="source-note ${p.status==='warn'?'warn':''}"><strong>Quellenhinweis</strong>${p.note}</div>`:''}<div class="source-note"><strong>Quelle</strong>${p.source}</div></details></article>`}
function render(){const g=gradeFilter.value,d=dayFilter.value,t=typeFilter.value;const list=programs.filter(p=>(g==='all'||p.grades.includes(+g))&&(d==='all'||p.day===d)&&(t==='all'||p.type===t));programGrid.innerHTML=list.map(card).join('');resultCount.textContent=`${list.length} Angebote sichtbar.`}
function renderFirst(){const list=programs.filter(p=>p.grades.includes(1));firstGradeGrid.innerHTML=list.map(p=>`<article class="mini"><b>${p.name}</b><span>${dayNames[p.day]} · ${p.time}</span><span>${p.cost}</span></article>`).join('');statAll.textContent=programs.length;statFirst.textContent=list.length}
[gradeFilter,dayFilter,typeFilter].forEach(x=>x.addEventListener('change',render));resetFilters.addEventListener('click',()=>{gradeFilter.value=dayFilter.value=typeFilter.value='all';render()});render();renderFirst();