const programs=[
{id:'zirkus',name:'Cirkuszszínház',type:'muveszet',grades:[2],day:'MO',time:'15:00–16:50',start:'2026.09.21.',end:'2027.06.21.',place:'Tornaterem',cost:'ingyenes',contact:'Jelentkezés az osztálytanítón keresztül.',summary:'Cirkuszi-színházi foglalkozás a 2. osztály számára.',source:'Iskolai Excel-összesítő',status:'ok'},
{id:'italiano-a',name:'Olasz – kezdő',type:'nyelv',grades:[2,3,4],day:'MO',time:'15:00–15:50',start:'2026.09.21.',end:'2027.06.21.',place:'Nincs megadva',cost:'ingyenes',contact:'Jelentkezés az osztálytanítón keresztül.',summary:'Kezdő olasz nyelvi foglalkozás 2–4. osztályosoknak.',source:'Iskolai Excel-összesítő',status:'ok'},
{id:'italiano-f',name:'Olasz – haladó',type:'nyelv',grades:[2,3,4],day:'MO',time:'16:00–16:50',start:'2026.09.21.',end:'2027.06.21.',place:'Nincs megadva',cost:'ingyenes',contact:'Jelentkezés az osztálytanítón keresztül.',summary:'Haladó olasz nyelvi foglalkozás 2–4. osztályosoknak.',source:'Iskolai Excel-összesítő',status:'ok'},
{id:'football-girls',name:'Football School – lányok',type:'sport',grades:[1,2,3,4],day:'MO',time:'Excel: 17:00–17:50 · plakát: 17:00–18:00',start:'2026.10.05.',end:'Téli félévi dátumlista a plakáton',place:'Tornaterem',cost:'Excel: 169 € / 12 alkalom',contact:'https://www.footballschool.at · +43 676 3239024 · office@footballschool.at',summary:'Lány focikurzus 1–4. osztályosoknak.',source:'Iskolai Excel + Football School plakát',status:'warn',note:'A nyomtatott plakát hétfőn 17:00–18:00 időt és 2026.10.05-i kezdést ír. Az Excel 17:00–17:50-et és 169 € / 12 alkalmat tartalmaz. A plakáton kézzel 169 € és testvérkedvezményre utaló megjegyzés látható; ezt nem kezeljük nyomtatott, garantált feltételként.'},
{id:'football-boys',name:'Football School – fiúk',type:'sport',grades:[1,2,3,4],day:'DI',time:'Excel: 17:00–17:50 · plakát: 17:00–18:00',start:'2026.09.29.',end:'Téli félévi dátumlista a plakáton',place:'Tornaterem',cost:'Excel: 169 € / 12 alkalom',contact:'https://www.footballschool.at · +43 676 3239024 · office@footballschool.at',summary:'Fiú focikurzus 1–4. osztályosoknak.',source:'Iskolai Excel + Football School plakát',status:'warn',note:'A nyomtatott plakát kedden 17:00–18:00 időt és 2026.09.29-i kezdést ír. Az Excel 17:00–17:50-et tartalmaz. A két kezdődátum nem alternatíva: 05.10. a lányok, 29.09. a fiúk kezdése.'},
{id:'singschule-di',name:'Singschule Wien – kedd',type:'zene',grades:[2,3,4],day:'DI',time:'13:00–15:50, csoporttól függően',start:'Nincs külön kezdődátum megadva',end:'2026/27-es tanév',place:'3. emelet · Top 31 / Top 38',cost:'Nincs díj megadva',contact:'0699 12460260 · személyes jelentkezés: 2026.09.18. 17:00–18:30, Top 38',summary:'Zongora és Wiener Kinderstimmen énekcsoportok 2–4. osztályosoknak.',source:'Singschule Wien tájékoztató',status:'ok',note:'Kedd: 13:00–13:50 zongora; 14:00–14:50 ének a 2. osztálynak; 15:00–15:50 ének a 3–4. osztálynak. A lap szerint a zongora, zeneismeret és hangképzés 2., 3. és 4. osztályosoknak szól.'},
{id:'schach',name:'Sakk',type:'strategia',grades:[1,2,3,4],day:'MI',time:'Excel: 15:00–15:50 · szórólap: 13:00–15:50',start:'2026.10.07.',end:'2027.05.26.',place:'Top 30',cost:'119 € / félév · 219 € / tanév',contact:'https://www.schachkurse.at/anmeldung · schachkurse@spids.at',summary:'Iskolai sakk 1–4. osztályosoknak, online előjelentkezéssel.',source:'Iskolai Excel + Schulschach szórólap',status:'warn',note:'A részletes szórólap 13:00–15:50 közötti kurzusablakot ad meg, az Excel 15:00–15:50-et. Ezt csoportbeosztástól függő, megerősítendő adatként kezeljük. A szórólap szerinti jelentkezési határidő 2026.10.03.'},
{id:'tennis',name:'Tenisz',type:'sport',grades:[1,2,3,4],day:'MI',time:'17:00–17:50',start:'2026 október – pontos nap nincs megadva',end:'2027.05.01. az Excel szerint',place:'Tornaterem',cost:'125 € / min. 12 alkalom · 230 € / min. 24 alkalom',contact:'https://www.tennis4everyone.at · office@tennis4everyone.at',summary:'Teniszfoglalkozás 1–4. osztályosoknak.',source:'Iskolai Excel-összesítő',status:'warn',note:'A kezdés mezőben csak „Oktober 26” szerepel, pontos nap nélkül. A végdátum 2027.05.01. az Excelből származik.'},
{id:'kunst-1',name:'Kreatív Művészeti Klub – 1. osztály',type:'muveszet',grades:[1],day:'MI',time:'15:00–15:50',start:'2026.09.30.',end:'Forrásadat ellenőrizendő',place:'Top 33',cost:'50 € / hó, anyaggal együtt',contact:'potteryclubvienna@gmail.com',summary:'Kreatív művészeti klub kifejezetten 1. osztályosoknak.',source:'Iskolai Excel-összesítő',status:'warn',note:'Az Excel végdátumként 2026.05.01-et tartalmaz, ami korábbi a 2026.09.30-i kezdésnél. A tényleges záródátumot a szervezőnek kell megerősítenie.'},
{id:'kunst-all',name:'Kreatív Művészeti Klub – 1–4. osztály',type:'muveszet',grades:[1,2,3,4],day:'MI',time:'16:00–17:30',start:'2026.09.30.',end:'Forrásadat ellenőrizendő',place:'Top 33',cost:'60 € / hó, anyaggal együtt',contact:'potteryclubvienna@gmail.com',summary:'Hosszabb kreatív művészeti foglalkozás 1–4. osztályosoknak.',source:'Iskolai Excel-összesítő',status:'warn',note:'Az Excel ennél a sornál is 2026.05.01-i végdátumot tartalmaz, vagyis korábbit a kezdésnél.'},
{id:'motopaed',name:'Motopedagógia',type:'fejlesztes',grades:[1,2,3,4],day:'DO',time:'17:00–17:50',start:'Nincs megadva',end:'Nincs megadva',place:'Tornaterem',cost:'Nincs megadva',contact:'Verein AKMÖ · katharina.loy@hotmail.com',summary:'Mozgásos, pszichomotoros jellegű foglalkozás 1–4. osztályosoknak.',source:'Iskolai Excel-összesítő',status:'warn',note:'A forrás nem ad kezdési/végdátumot és díjat.'},
{id:'singschule-do',name:'Singschule Wien – csütörtök',type:'zene',grades:[2,3,4],day:'DO',time:'12:00–16:50, csoporttól függően',start:'Nincs külön kezdődátum megadva',end:'2026/27-es tanév',place:'3. emelet · Top 31 / Top 38',cost:'Nincs díj megadva',contact:'0699 12460260 · személyes jelentkezés: 2026.09.18. 17:00–18:30, Top 38',summary:'Zongora, zeneismeret és hangképzés 2–4. osztályosoknak.',source:'Singschule Wien tájékoztató',status:'ok',note:'Csütörtök: 12:00–12:50 zongora; 13:00–13:50, 14:00–14:50 és 15:00–15:50 zeneismeret/hangképzés; 16:00–16:50 zongora. A kiscsoportokat egyeztetés után osztják be.'},
{id:'piano-wagner',name:'Zongora – Negar Wagner',type:'zene',grades:[1,2,3,4],day:'DO',time:'12:00–17:00 közötti egyéni időpont',start:'Excel: 2025.09.25.',end:'Excel: 2026.06.01.',place:'Top 11',cost:'24 € / 25 perc egyéni óra',contact:'negar.wagner@gmail.com',summary:'25 perces egyéni zongoraóra 1–4. osztályosoknak.',source:'Iskolai Excel-összesítő',status:'warn',note:'A dátumok a 2025/26-os tanévre mutatnak, miközben a fájl 2026/27-es összesítőként érkezett. Aktuális megerősítés szükséges.'}
];
const dayNames={MO:'Hétfő',DI:'Kedd',MI:'Szerda',DO:'Csütörtök'},typeNames={sport:'Sport',zene:'Zene',muveszet:'Művészet',nyelv:'Nyelv',fejlesztes:'Fejlesztés',strategia:'Stratégia'};
function linkify(text){const m=text.match(/https?:\/\/[^ ·]+/);if(!m)return text;return `<a href="${m[0]}" target="_blank" rel="noopener">Jelentkezési oldal</a><br>${text.replace(m[0],'').replace(/^ · /,'')}`}
function card(p){const grades=p.grades.length===1?`${p.grades[0]}. osztály`:`${p.grades[0]}–${p.grades.at(-1)}. osztály`;return `<article class="card"><div class="card-head"><div><h3>${p.name}</h3><p class="summary">${p.summary}</p></div><span class="badge ${p.status==='warn'?'warn':''}">${p.status==='warn'?'Ellenőrizendő':'Forrás szerint'}</span></div><div class="chips"><span class="chip">${grades}</span><span class="chip">${dayNames[p.day]}</span><span class="chip">${p.time}</span><span class="chip">${typeNames[p.type]}</span></div><details class="details"><summary>Részletek</summary><ul class="kv"><li><span class="k">Időpont</span><span>${dayNames[p.day]} · ${p.time}</span></li><li><span class="k">Kezdés</span><span>${p.start}</span></li><li><span class="k">Vége</span><span>${p.end}</span></li><li><span class="k">Helyszín</span><span>${p.place}</span></li><li><span class="k">Díj</span><span>${p.cost}</span></li><li><span class="k">Jelentkezés</span><span>${linkify(p.contact)}</span></li></ul>${p.note?`<div class="source-note ${p.status==='warn'?'warn':''}"><strong>Forrásmagyarázat</strong>${p.note}</div>`:''}<div class="source-note"><strong>Forrás</strong>${p.source}</div></details></article>`}
function render(){const g=gradeFilter.value,d=dayFilter.value,t=typeFilter.value;const list=programs.filter(p=>(g==='all'||p.grades.includes(+g))&&(d==='all'||p.day===d)&&(t==='all'||p.type===t));programGrid.innerHTML=list.map(card).join('');resultCount.textContent=`${list.length} program látható.`}
function renderFirst(){const list=programs.filter(p=>p.grades.includes(1));firstGradeGrid.innerHTML=list.map(p=>`<article class="mini"><b>${p.name}</b><span>${dayNames[p.day]} · ${p.time}</span><span>${p.cost}</span></article>`).join('');statAll.textContent=programs.length;statFirst.textContent=list.length}
function initMenu(){const nav=document.querySelector('.nav');if(!nav||nav.closest('.menu-shell'))return;const labels={'#programok':'Iskolai programok','#elso-osztaly':'1. osztályos programok','https://programvalaszto.magyariskola.at/':'Bécsi Magyar Iskola – magyar nyelvű foglalkozások','https://www.becsinaplo.at/post/tobb-mint-egyesuleti-iskolak-a-magyaroktatas-uj-utjai-becsben':'Bécsi Napló – A magyar oktatás új útjai','#plakat-audit':'Plakátok és forrásellenőrzés','#forrasok':'Források és adatértelmezés'};nav.querySelectorAll('a').forEach(a=>{const key=a.getAttribute('href');if(labels[key])a.textContent=labels[key]});nav.setAttribute('aria-label','Menü');const shell=document.createElement('details');shell.className='menu-shell';const summary=document.createElement('summary');summary.textContent='Menü';summary.setAttribute('aria-label','Menü megnyitása');shell.append(summary);nav.parentNode.insertBefore(shell,nav);shell.append(nav);nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>shell.removeAttribute('open')));document.addEventListener('keydown',e=>{if(e.key==='Escape')shell.removeAttribute('open')});document.addEventListener('click',e=>{if(shell.open&&!shell.contains(e.target))shell.removeAttribute('open')})}
[gradeFilter,dayFilter,typeFilter].forEach(x=>x.addEventListener('change',render));resetFilters.addEventListener('click',()=>{gradeFilter.value=dayFilter.value=typeFilter.value='all';render()});initMenu();render();renderFirst();