const programs=[
{id:'zirkus',name:'Zirkustheater',type:'muveszet',grades:[2],day:'MO',time:'15:00–16:50',start:'2026.09.21.',end:'2027.06.21.',place:'Turnsaal',cost:'ingyenes',contact:'Jelentkezés az osztálytanítón keresztül.',summary:'Cirkuszi-színházi foglalkozás a 2. osztály számára.',source:'Excel-összesítő',status:'ok'},
{id:'italiano-a',name:'Olasz – kezdő',type:'nyelv',grades:[2,3,4],day:'MO',time:'15:00–15:50',start:'2026.09.21.',end:'2027.06.21.',place:'Nincs megadva',cost:'ingyenes',contact:'Jelentkezés az osztálytanítón keresztül.',summary:'Kezdő olasz nyelvi foglalkozás 2–4. osztályosoknak.',source:'Excel-összesítő',status:'ok'},
{id:'italiano-f',name:'Olasz – haladó',type:'nyelv',grades:[2,3,4],day:'MO',time:'16:00–16:50',start:'2026.09.21.',end:'2027.06.21.',place:'Nincs megadva',cost:'ingyenes',contact:'Jelentkezés az osztálytanítón keresztül.',summary:'Haladó olasz nyelvi foglalkozás 2–4. osztályosoknak.',source:'Excel-összesítő',status:'ok'},
{id:'football-girls',name:'Football School – lányok',type:'sport',grades:[1,2,3,4],day:'MO',time:'17:00–17:50 az Excel szerint',start:'2026.10.05.',end:'A szórólap téli félévi dátumlistát ad meg',place:'Turnsaal',cost:'169 € / 12 alkalom az Excel szerint',contact:'https://www.footballschool.at · +43 676 3239024 · office@footballschool.at',summary:'Lány focikurzus 1–4. osztályosoknak. A részletes szórólap 17:00–18:00 időt ír.',source:'Excel + Football School szórólap',status:'warn',note:'Eltérés: az Excel 17:00–17:50-et, a részletes szórólap 17:00–18:00-t ír. A szórólapon a következő hétfői dátumok látszanak: 05.10., 12.10., 19.10., 09.11., 16.11., 23.11., 30.11., 07.12., 14.12., 21.12., 11.01., 18.01.; 26.10., 02.11., 28.12. és 04.01. „frei” jelölésű. Jelentkezés előtt az aktuális időt érdemes a Football Schoolnál megerősíteni.'},
{id:'football-boys',name:'Football School – fiúk',type:'sport',grades:[1,2,3,4],day:'DI',time:'17:00–17:50 az Excel szerint',start:'2026.09.29.',end:'A szórólap téli félévi dátumlistát ad meg',place:'Turnsaal',cost:'169 € / 12 alkalom az Excel szerint',contact:'https://www.footballschool.at · +43 676 3239024 · office@footballschool.at',summary:'Fiú focikurzus 1–4. osztályosoknak. A részletes szórólap 17:00–18:00 időt ír.',source:'Excel + Football School szórólap',status:'warn',note:'Eltérés: az Excel 17:00–17:50-et, a részletes szórólap 17:00–18:00-t ír. A szórólapon keddi téli félévi dátumok szerepelnek, több szüneti nappal. Jelentkezés előtt az aktuális időt érdemes a Football Schoolnál megerősíteni.'},
{id:'singschule-di',name:'Singschule Wien – kedd',type:'zene',grades:[2,3,4],day:'DI',time:'13:00–15:50, csoporttól függően',start:'Nincs külön tanévkezdési dátum megadva',end:'2026/27-es tanév',place:'3. emelet · Top 31 / Top 38',cost:'A lapon nincs díj megadva',contact:'0699 12460260 · személyes jelentkezés: 2026.09.18. 17:00–18:30, Top 38',summary:'Keddi zenei kínálat: zongora és Wiener Kinderstimmen énekcsoportok 2–4. osztályosoknak.',source:'Singschule Wien részletes tájékoztató',status:'ok',note:'Kedd: 13:00–13:50 zongora (Prisender); 14:00–14:50 ének / Wiener Kinderstimmen, 2. osztály (Prisender + Cena); 15:00–15:50 ének, 3–4. osztály (Prisender + Cena). A tájékoztató szerint a zongora, zeneismeret és hangképzés 2., 3. és 4. osztályosoknak szól.'},
{id:'schach',name:'Sakk',type:'strategia',grades:[1,2,3,4],day:'MI',time:'Excel: 15:00–15:50 · szórólap: 13:00–15:50',start:'2026.10.07.',end:'2027.05.26.',place:'Top 30',cost:'119 € / félév · 219 € / tanév',contact:'https://www.schachkurse.at/anmeldung · schachkurse@spids.at',summary:'Iskolai sakk 1–4. osztályosoknak, online előjelentkezéssel és próbaalkalom lehetőségével.',source:'Excel + Schulschach szórólap',status:'warn',note:'A részletes szórólap szerda 13:00–15:50 közötti kurzusablakot ad meg, míg az Excel 15:00–15:50-et. Valószínűleg csoportbeosztás történik, ezért a pontos gyermek-idősávot a szervező erősíti meg. A szórólap szerint jelentkezési határidő: 2026.10.03.; a tanév egészére 219 €, az 1. félévre 119 €.'},
{id:'tennis',name:'Tenisz',type:'sport',grades:[1,2,3,4],day:'MI',time:'17:00–17:50',start:'2026 október – pontos nap nincs egyértelműen megadva',end:'Az Excelben 2027.05.01. szerepel',place:'Turnsaal',cost:'125 € / min. 12 alkalom · 230 € / min. 24 alkalom',contact:'https://www.tennis4everyone.at · office@tennis4everyone.at',summary:'Teniszfoglalkozás 1–4. osztályosoknak.',source:'Excel-összesítő',status:'warn',note:'A kezdés mezőben „Okotober 26” szerepel, ami nem ad pontos napot. A végdátum 2027.05.01. az Excelből származik. Jelentkezés előtt kérjetek pontos dátumot a szolgáltatótól.'},
{id:'kunst-1',name:'Kreativer Kunst Klub – 1. osztály',type:'muveszet',grades:[1],day:'MI',time:'15:00–15:50',start:'2026.09.30.',end:'Forrásadat ellenőrizendő',place:'Top 33',cost:'50 € / hó, anyaggal együtt',contact:'potteryclubvienna@gmail.com',summary:'Kreatív művészeti klub kifejezetten 1. osztályosoknak.',source:'Excel-összesítő',status:'warn',note:'Az Excel végdátumként 2026.05.01-et tartalmaz, ami korábbi a 2026.09.30-i kezdésnél. Ezt nem javítottuk találgatással; a tényleges záródátumot a szervezőtől kell megerősíteni.'},
{id:'kunst-all',name:'Kreativer Kunst Klub – 1–4. osztály',type:'muveszet',grades:[1,2,3,4],day:'MI',time:'16:00–17:30',start:'2026.09.30.',end:'Forrásadat ellenőrizendő',place:'Top 33',cost:'60 € / hó, anyaggal együtt',contact:'potteryclubvienna@gmail.com',summary:'Hosszabb kreatív művészeti foglalkozás 1–4. osztályosoknak.',source:'Excel-összesítő',status:'warn',note:'Az Excel végdátuma ennél a sornál is korábbi a kezdésnél, ezért a tényleges időszakot a szervezővel kell ellenőrizni.'},
{id:'motopaed',name:'Motopädagogik',type:'fejlesztes',grades:[1,2,3,4],day:'DO',time:'17:00–17:50',start:'Nincs megadva',end:'Nincs megadva',place:'Turnsaal',cost:'Nincs megadva',contact:'Verein AKMÖ · katharina.loy@hotmail.com',summary:'Mozgásos, pszichomotoros jellegű foglalkozás 1–4. osztályosoknak; az Excelben több részlet nincs kitöltve.',source:'Excel-összesítő',status:'warn',note:'A forrás nem ad kezdési/végdátumot és díjat. Ezeket jelentkezés előtt a Verein AKMÖ-nél kell tisztázni.'},
{id:'singschule-do',name:'Singschule Wien – csütörtök',type:'zene',grades:[2,3,4],day:'DO',time:'12:00–16:50, csoporttól függően',start:'Nincs külön tanévkezdési dátum megadva',end:'2026/27-es tanév',place:'3. emelet · Top 31 / Top 38',cost:'A lapon nincs díj megadva',contact:'0699 12460260 · személyes jelentkezés: 2026.09.18. 17:00–18:30, Top 38',summary:'Csütörtöki zongora, zeneismeret és hangképzés 2–4. osztályosoknak.',source:'Singschule Wien részletes tájékoztató',status:'ok',note:'Csütörtök: 12:00–12:50 zongora; 13:00–13:50, 14:00–14:50 és 15:00–15:50 Musikkunde / Stimmbildung; 16:00–16:50 zongora. A kiscsoportokat egyeztetés után osztják be.'},
{id:'piano-wagner',name:'Zongora – Negar Wagner',type:'zene',grades:[1,2,3,4],day:'DO',time:'12:00–17:00 közötti egyéni időpont',start:'Az Excelben 2025.09.25. szerepel',end:'Az Excelben 2026.06.01. szerepel',place:'Top 11',cost:'24 € / 25 perc egyéni óra',contact:'negar.wagner@gmail.com',summary:'25 perces egyéni zongoraóra 1–4. osztályosoknak.',source:'Excel-összesítő',status:'warn',note:'A kezdés és a vég az Excelben a 2025/26-os tanévre mutat, miközben a fájl 2026/27-es összesítőként érkezett. Ezért ezt az ajánlatot csak aktuális megerősítés után érdemes választani.'}
];
const dayNames={MO:'Hétfő',DI:'Kedd',MI:'Szerda',DO:'Csütörtök'};const typeNames={sport:'Sport',zene:'Zene',muveszet:'Művészet',nyelv:'Nyelv',fejlesztes:'Fejlesztés',strategia:'Stratégia'};
function safeLink(text){if(text.includes('http')){const url=text.match(/https?:\/\/[^ ·]+/);return url?`<a href="${url[0]}" target="_blank" rel="noopener">Jelentkezési oldal</a><br>${text.replace(url[0],'').replace(/^ · /,'')}`:text}return text}
function card(p){const grades=p.grades.length===1?`${p.grades[0]}. osztály`:`${p.grades[0]}–${p.grades[p.grades.length-1]}. osztály`;return `<article class="card" data-grade="${p.grades.join(',')}" data-day="${p.day}" data-type="${p.type}"><div class="card-head"><div><h3>${p.name}</h3><p class="summary">${p.summary}</p></div><span class="badge ${p.status==='warn'?'warn':''}">${p.status==='warn'?'Ellenőrizendő':'Forrás szerint'}</span></div><div class="chips"><span class="chip">${grades}</span><span class="chip">${dayNames[p.day]}</span><span class="chip">${p.time}</span><span class="chip">${typeNames[p.type]}</span></div><details class="details"><summary>Részletek</summary><ul class="kv"><li><span class="k">Időpont</span><span>${dayNames[p.day]} · ${p.time}</span></li><li><span class="k">Kezdés</span><span>${p.start}</span></li><li><span class="k">Vége</span><span>${p.end}</span></li><li><span class="k">Helyszín</span><span>${p.place}</span></li><li><span class="k">Díj</span><span>${p.cost}</span></li><li><span class="k">Jelentkezés</span><span>${safeLink(p.contact)}</span></li></ul>${p.note?`<div class="source-note ${p.status==='warn'?'warn':''}"><strong>Forrásmagyarázat</strong>${p.note}</div>`:''}<div class="source-note"><strong>Forrás</strong>${p.source}</div></details></article>`}
function render(){const g=document.getElementById('gradeFilter').value,d=document.getElementById('dayFilter').value,t=document.getElementById('typeFilter').value;const filtered=programs.filter(p=>(g==='all'||p.grades.includes(Number(g)))&&(d==='all'||p.day===d)&&(t==='all'||p.type===t));document.getElementById('programGrid').innerHTML=filtered.map(card).join('');document.getElementById('resultCount').textContent=`${filtered.length} program látható.`}
function renderFirst(){const first=programs.filter(p=>p.grades.includes(1));document.getElementById('firstGradeGrid').innerHTML=first.map(p=>`<article class="mini"><b>${p.name}</b><span>${dayNames[p.day]} · ${p.time}</span><span>${p.cost}</span></article>`).join('');document.getElementById('statAll').textContent=programs.length;document.getElementById('statFirst').textContent=first.length}
['gradeFilter','dayFilter','typeFilter'].forEach(id=>document.getElementById(id).addEventListener('change',render));document.getElementById('resetFilters').addEventListener('click',()=>{['gradeFilter','dayFilter','typeFilter'].forEach(id=>document.getElementById(id).value='all');render()});render();renderFirst();
