(function(){
'use strict';
var lang=(document.documentElement.lang||'hu').toLowerCase();
var L=lang.indexOf('de')===0?{
 title:'Entfernung zu den Programmen',intro:'Startadresse eingeben und Entfernung bzw. Fahrzeit zu den Programmorten berechnen.',address:'Startadresse',placeholder:'z. B. 1180 Wien, Währinger Straße 100',car:'Auto',walk:'Zu Fuß',transit:'Öffis',calc:'Entfernungen berechnen',current:'Mein Standort',consent:'Genaue Adresse und Routenberechnung erlauben',privacy:'Die Adresse wird nicht gespeichert. Mit Zustimmung werden Adressdaten nur für Geokodierung und Routing an Photon/Komoot und OpenStreetMap übertragen.',statusReady:'Adresse erkannt. Entfernungen werden berechnet…',statusFail:'Die Adresse konnte nicht eindeutig gefunden werden.',statusConsent:'Bitte zuerst die Karten- und Routendatenverarbeitung erlauben.',route:'Route',maps:'Google Maps',schoolMap:'Schulstandort',schoolNote:'Schuladresse; der genaue Raum ist in der Programmbeschreibung angegeben.',distanceUnavailable:'Entfernung nicht automatisch berechenbar',searchLocation:'Standortsuche',multiple:'Standorte',km:'km',min:'Min.'
}:lang.indexOf('en')===0?{
 title:'Distance to programmes',intro:'Enter a starting address to calculate distance and travel time to programme locations.',address:'Starting address',placeholder:'e.g. 1180 Vienna, Währinger Straße 100',car:'Car',walk:'Walk',transit:'Public transport',calc:'Calculate distances',current:'My location',consent:'Allow precise address and route calculation',privacy:'The address is not stored. With consent, address data is sent only as needed for geocoding and routing to Photon/Komoot and OpenStreetMap.',statusReady:'Address identified. Calculating distances…',statusFail:'The address could not be identified unambiguously.',statusConsent:'Please allow map and route data processing first.',route:'Route',maps:'Google Maps',schoolMap:'School location',schoolNote:'School address; the exact room is shown in the programme details.',distanceUnavailable:'Distance cannot be calculated automatically',searchLocation:'Location search',multiple:'Locations',km:'km',min:'min'
}:{
 title:'Távolság a programokhoz',intro:'Add meg a kiindulási címet, és az app kiszámolja a programhelyszínek távolságát és menetidejét.',address:'Kiindulási cím',placeholder:'pl. 1180 Wien, Währinger Straße 100',car:'Autóval',walk:'Gyalog',transit:'Tömegközlekedéssel',calc:'Távolságok kiszámítása',current:'Jelenlegi helyzetem',consent:'Pontos cím és útvonalszámítás engedélyezése',privacy:'A címet nem mentjük el. Hozzájárulás után a címadat csak a geokódoláshoz és útvonalszámításhoz szükséges mértékben kerül a Photon/Komoot és OpenStreetMap szolgáltatásaihoz.',statusReady:'Cím azonosítva. Távolságok számítása…',statusFail:'A címet nem sikerült egyértelműen azonosítani.',statusConsent:'Előbb engedélyezd a térképes és útvonal-adatkezelést.',route:'Útvonal',maps:'Google Maps',schoolMap:'Iskola térképen',schoolNote:'Az iskola címe; a pontos terem a program részleteinél szerepel.',distanceUnavailable:'A távolság automatikusan nem számítható',searchLocation:'Helyszínkeresés',multiple:'Helyszínek',km:'km',min:'perc'};
var SCHOOL='Schulgasse 57, 1180 Wien, Austria';
var cache={},routeCache={};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function mapsUrl(dest,origin,mode){var q='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(dest);if(origin)q+='&origin='+encodeURIComponent(origin.label||origin.raw||'');if(mode)q+='&travelmode='+(mode==='walk'?'walking':mode==='transit'?'transit':'driving');return q}
function mapLink(label,dest,exact){return '<a class="map-destination" href="'+mapsUrl(dest)+'" target="_blank" rel="noopener noreferrer" data-map-dest="'+esc(dest)+'" data-map-exact="'+(exact?'1':'0')+'"><span>'+esc(label)+'</span><small>'+L.maps+'</small><em class="distance-result"></em></a>'}
function addStyles(){if(document.getElementById('distance-system-style'))return;var s=document.createElement('style');s.id='distance-system-style';s.textContent='.distance-panel{margin:28px auto 0;padding:22px;border:1px solid rgba(0,0,0,.10);border-radius:20px;background:#fff;box-shadow:0 12px 32px rgba(0,0,0,.05)}.distance-panel h2{margin:0 0 6px}.distance-panel p{margin:0 0 14px}.distance-form{display:grid;gap:12px}.distance-row{display:flex;gap:10px;flex-wrap:wrap;align-items:center}.distance-input{flex:1 1 320px;min-width:0;padding:12px 14px;border:1px solid #c7c7cc;border-radius:12px;font:inherit}.distance-mode{min-height:44px;padding:10px 14px;border:1px solid #c7c7cc;border-radius:999px;background:#fff;font:inherit;cursor:pointer}.distance-mode.active{border-color:#111;background:#111;color:#fff}.distance-consent{display:flex;gap:10px;align-items:flex-start;font-size:.9rem;line-height:1.45}.distance-consent input{margin-top:3px}.distance-status{min-height:1.4em;font-size:.9rem}.map-destination{display:inline-flex;flex-direction:column;gap:2px;margin:6px 8px 2px 0;padding:9px 11px;border:1px solid rgba(0,0,0,.12);border-radius:12px;text-decoration:none!important;vertical-align:top;max-width:100%}.map-destination span{font-weight:650}.map-destination small{font-size:.74rem;opacity:.65}.map-destination em{font-style:normal;font-size:.82rem;font-weight:650;margin-top:2px}.map-destination.pending em:after{content:" …"}.map-note{display:block;font-size:.78rem;opacity:.65;margin-top:4px}.map-destinations{margin-top:10px}.location-map-wrap{display:block;margin-top:6px}@media(max-width:640px){.distance-panel{padding:16px;border-radius:16px}.distance-row>*{width:100%}.distance-mode{width:auto;flex:1}.map-destination{display:flex;margin-right:0}}';document.head.appendChild(s)}
function exactSchoolCards(root){(root||document).querySelectorAll('.card .kv li').forEach(function(li){var k=li.querySelector('.k');if(!k)return;var key=(k.textContent||'').trim().toLowerCase();if(key!=='helyszín'&&key!=='ort'&&key!=='location')return;var val=k.nextElementSibling;if(!val||val.dataset.mapDone)return;val.dataset.mapDone='1';var txt=(val.textContent||'').trim();var unknown=/nincs megadva|nicht angegeben|not specified/i.test(txt);if(unknown){val.insertAdjacentHTML('beforeend','<span class="location-map-wrap">'+mapLink(L.schoolMap,SCHOOL,true)+'<small class="map-note">'+esc(L.schoolNote)+'</small></span>')}else{val.innerHTML=mapLink(txt,SCHOOL,true)+'<small class="map-note">'+esc(L.schoolNote)+'</small>'}})}
var CITY={
 'Wiener Lernhilfe – LernMinis':[{l:'VHS Wien',d:'VHS Wien, Wien, Austria',x:false}],
 'Wiener KinderStimmen / Singschule Wien':[{l:'Singschule Wien',d:'Singschule Wien, Wien, Austria',x:false}],
 'Musikschulen Wien – hangszer, zene, kórus':[{l:'Musikschulen Wien',d:'Musikschulen Wien, Wien, Austria',x:false}],
 'Musikschulen Wien – Instrumente, Gesang und Ensembles':[{l:'Musikschulen Wien',d:'Musikschulen Wien, Wien, Austria',x:false}],
 'Vienna Music Schools – instruments, singing and ensembles':[{l:'Vienna Music Schools',d:'Musikschulen Wien, Wien, Austria',x:false}],
 'Tánc – Musikschulen Wien':[{l:'Leopoldstadt',d:'Taborstraße 120, 1020 Wien, Austria',x:true},{l:'Landstraße',d:'Otto-Preminger-Straße 1, 1030 Wien, Austria',x:true},{l:'Donaustadt',d:'Natorpgasse 1, 1220 Wien, Austria',x:true},{l:'Liesing',d:'Josef-Kutscha-Gasse 1A, 1230 Wien, Austria',x:true},{l:'Inkluzív tánc/theater',d:'Erlaaer Straße 74, 1230 Wien, Austria',x:true}],
 'Tanz – Musikschulen Wien':[{l:'Leopoldstadt',d:'Taborstraße 120, 1020 Wien, Austria',x:true},{l:'Landstraße',d:'Otto-Preminger-Straße 1, 1030 Wien, Austria',x:true},{l:'Donaustadt',d:'Natorpgasse 1, 1220 Wien, Austria',x:true},{l:'Liesing',d:'Josef-Kutscha-Gasse 1A, 1230 Wien, Austria',x:true},{l:'Tanz/Theater inklusiv',d:'Erlaaer Straße 74, 1230 Wien, Austria',x:true}],
 'Dance – Vienna Music Schools':[{l:'Leopoldstadt',d:'Taborstraße 120, 1020 Wien, Austria',x:true},{l:'Landstraße',d:'Otto-Preminger-Straße 1, 1030 Wien, Austria',x:true},{l:'Donaustadt',d:'Natorpgasse 1, 1220 Wien, Austria',x:true},{l:'Liesing',d:'Josef-Kutscha-Gasse 1A, 1230 Wien, Austria',x:true},{l:'Inclusive dance/theatre',d:'Erlaaer Straße 74, 1230 Wien, Austria',x:true}],
 'Talente-Schwimmkurse – őszi/téli félév 2026':[{l:'Amalienbad',d:'Amalienbad, Reumannplatz 23, 1100 Wien, Austria',x:true},{l:'Brigittenauer Bad',d:'Brigittenauer Bad, Klosterneuburger Straße 93-97, 1200 Wien, Austria',x:true},{l:'Floridsdorfer Bad',d:'Floridsdorfer Bad, Franklinstraße 22, 1210 Wien, Austria',x:true}],
 'Talente-Schwimmkurse – Wintersemester 2026':[{l:'Amalienbad',d:'Amalienbad, Reumannplatz 23, 1100 Wien, Austria',x:true},{l:'Brigittenauer Bad',d:'Brigittenauer Bad, Klosterneuburger Straße 93-97, 1200 Wien, Austria',x:true},{l:'Floridsdorfer Bad',d:'Floridsdorfer Bad, Franklinstraße 22, 1210 Wien, Austria',x:true}],
 'Talente swimming courses – winter semester 2026':[{l:'Amalienbad',d:'Amalienbad, Reumannplatz 23, 1100 Wien, Austria',x:true},{l:'Brigittenauer Bad',d:'Brigittenauer Bad, Klosterneuburger Straße 93-97, 1200 Wien, Austria',x:true},{l:'Floridsdorfer Bad',d:'Floridsdorfer Bad, Franklinstraße 22, 1210 Wien, Austria',x:true}],
 'Stadt Wien Bäder – csoportos úszásoktatás':[{l:'Stadt Wien Bäder',d:'Stadt Wien Bäder, Wien, Austria',x:false}],
 'Stadt Wien Bäder – Gruppenschwimmkurse':[{l:'Stadt Wien Bäder',d:'Stadt Wien Bäder, Wien, Austria',x:false}],
 'City of Vienna pools – group swimming lessons':[{l:'City of Vienna pools',d:'Stadt Wien Bäder, Wien, Austria',x:false}],
 'Sport & Fun Hallen':[{l:'Donaustadt',d:'Erzherzog-Karl-Straße 108, 1220 Wien, Austria',x:true},{l:'Favoriten',d:'Windtenstraße 2, 1100 Wien, Austria',x:true},{l:'Leopoldstadt',d:'Venediger Au 11, 1020 Wien, Austria',x:true},{l:'Ottakring',d:'Sandleitengasse, 1160 Wien, Austria',x:true}],
 'Summer City Camps – városi nyári felügyelet':[{l:'Summer City Camps',d:'Summer City Camps Wien, Austria',x:false}],
 'Summer City Camps':[{l:'Summer City Camps',d:'Summer City Camps Wien, Austria',x:false}],
 'WIENXTRA Kinderaktiv':[{l:'WIENXTRA Kinderinfo',d:'Lassallestraße 3, 1020 Wien, Austria',x:true}],
 'WIENXTRA Ferienspiel':[{l:'WIENXTRA Kinderinfo',d:'Lassallestraße 3, 1020 Wien, Austria',x:true}],
 'Büchereien Wien – gyermekprogramok':[{l:'Büchereien Wien',d:'Urban-Loritz-Platz 2a, 1070 Wien, Austria',x:true}],
 'Büchereien Wien – Kinderprogramm':[{l:'Büchereien Wien',d:'Urban-Loritz-Platz 2a, 1070 Wien, Austria',x:true}],
 'Vienna Libraries – children’s programme':[{l:'Vienna Libraries',d:'Urban-Loritz-Platz 2a, 1070 Wien, Austria',x:true}],
 'Wiener Herbst Camps 2026':[{l:'Ferien in Wien',d:'Wiener Herbst Camps, Wien, Austria',x:false}]
};
function cityCards(){document.querySelectorAll('.program-grid>.card').forEach(function(card){if(card.querySelector('.kv')||card.dataset.mapCityDone)return;var h=card.querySelector('h3');if(!h)return;var items=CITY[(h.textContent||'').trim()];if(!items)return;card.dataset.mapCityDone='1';var box=document.createElement('div');box.className='map-destinations';box.innerHTML='<strong>'+esc(items.length>1?L.multiple:L.route)+'</strong><br>'+items.map(function(x){return mapLink(x.l,x.d,x.x)}).join('');card.appendChild(box)})}
function panel(){if(document.getElementById('distancePanel'))return;var hero=document.querySelector('.hero .wrap')||document.querySelector('main');if(!hero)return;var p=document.createElement('section');p.id='distancePanel';p.className='distance-panel';p.innerHTML='<h2>'+esc(L.title)+'</h2><p>'+esc(L.intro)+'</p><div class="distance-form"><label><strong>'+esc(L.address)+'</strong><br><input class="distance-input" id="distanceAddress" type="text" autocomplete="street-address" placeholder="'+esc(L.placeholder)+'"></label><label class="distance-consent"><input id="distanceConsent" type="checkbox"><span><strong>'+esc(L.consent)+'</strong><br>'+esc(L.privacy)+'</span></label><div class="distance-row" role="group"><button type="button" class="distance-mode active" data-dist-mode="car">'+esc(L.car)+'</button><button type="button" class="distance-mode" data-dist-mode="walk">'+esc(L.walk)+'</button><button type="button" class="distance-mode" data-dist-mode="transit">'+esc(L.transit)+'</button></div><div class="distance-row"><button type="button" class="btn" id="distanceCalc">'+esc(L.calc)+'</button><button type="button" class="btn ghost" id="distanceCurrent">'+esc(L.current)+'</button></div><div class="distance-status" id="distanceStatus" role="status"></div></div>';hero.appendChild(p);bindPanel()}
function fetchTimeout(url,ms){var c=typeof AbortController!=='undefined'?new AbortController():null,t=c?setTimeout(function(){c.abort()},ms||7000):null;return fetch(url,{headers:{Accept:'application/json'},signal:c?c.signal:void 0}).finally(function(){if(t)clearTimeout(t)})}
async function geocode(q){var key=q.toLowerCase();if(cache[key])return cache[key];try{var u='https://photon.komoot.io/api/?limit=5&lang=de&countrycode=AT&q='+encodeURIComponent(q),r=await fetchTimeout(u,6500);if(!r.ok)return null;var j=await r.json(),f=(j.features||[])[0];if(!f||!f.geometry)return null;var p={lat:+f.geometry.coordinates[1],lon:+f.geometry.coordinates[0],label:q};if(Number.isFinite(p.lat)&&Number.isFinite(p.lon)){cache[key]=p;return p}}catch(e){}return null}
function haversine(a,b){var R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lon-a.lon)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
async function route(origin,dest,mode){var k=[mode,origin.lat.toFixed(5),origin.lon.toFixed(5),dest.lat.toFixed(5),dest.lon.toFixed(5)].join('|');if(routeCache[k])return routeCache[k];if(mode==='transit')return null;var profile=mode==='walk'?'foot':'car';try{var u='https://routing.openstreetmap.de/routed-'+profile+'/route/v1/driving/'+origin.lon+','+origin.lat+';'+dest.lon+','+dest.lat+'?overview=false&alternatives=false&steps=false',r=await fetchTimeout(u,7000);if(r.ok){var j=await r.json(),rt=j.routes&&j.routes[0];if(rt){var out={km:rt.distance/1000,min:Math.max(1,Math.round(rt.duration/60)),estimated:false};routeCache[k]=out;return out}}}catch(e){}var straight=haversine(origin,dest),factor=mode==='walk'?1.22:1.28,speed=mode==='walk'?4.8:30,km=straight*factor,out={km:km,min:Math.max(1,Math.round(km/speed*60)),estimated:true};routeCache[k]=out;return out}
async function calculate(origin){var mode=document.querySelector('[data-dist-mode].active')?.dataset.distMode||'car',links=[].slice.call(document.querySelectorAll('.map-destination'));document.getElementById('distanceStatus').textContent=L.statusReady;for(var i=0;i<links.length;i++){var a=links[i],dest=a.dataset.mapDest,exact=a.dataset.mapExact==='1',res=a.querySelector('.distance-result');a.href=mapsUrl(dest,origin,mode);if(!exact){res.textContent=L.distanceUnavailable;continue}a.classList.add('pending');var g=await geocode(dest);if(!g){res.textContent=L.distanceUnavailable;a.classList.remove('pending');continue}if(mode==='transit'){var straight=haversine(origin,g);res.textContent=straight.toFixed(1)+' '+L.km+' · '+L.maps;a.classList.remove('pending');continue}var r=await route(origin,g,mode);res.textContent=r?(r.estimated?'≈ ':'')+r.km.toFixed(1)+' '+L.km+' · '+(r.estimated?'≈ ':'')+r.min+' '+L.min:L.distanceUnavailable;a.classList.remove('pending')};document.getElementById('distanceStatus').textContent=''}
function bindPanel(){var mode='car';document.querySelectorAll('[data-dist-mode]').forEach(function(b){b.addEventListener('click',function(){document.querySelectorAll('[data-dist-mode]').forEach(function(x){x.classList.remove('active')});b.classList.add('active');mode=b.dataset.distMode})});document.getElementById('distanceCalc').addEventListener('click',async function(){var consent=document.getElementById('distanceConsent'),st=document.getElementById('distanceStatus'),v=document.getElementById('distanceAddress').value.trim();if(!consent.checked){st.textContent=L.statusConsent;return}if(!v){st.textContent=L.statusFail;return}st.textContent=L.statusReady;var g=await geocode(v);if(!g){st.textContent=L.statusFail;return}g.label=v;calculate(g)});document.getElementById('distanceCurrent').addEventListener('click',function(){var st=document.getElementById('distanceStatus');if(!navigator.geolocation){st.textContent=L.statusFail;return}navigator.geolocation.getCurrentPosition(function(pos){calculate({lat:pos.coords.latitude,lon:pos.coords.longitude,label:''})},function(){st.textContent=L.statusFail},{enableHighAccuracy:false,timeout:8000,maximumAge:300000})})}
function enhance(){exactSchoolCards();cityCards()}
addStyles();panel();enhance();new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});
})();
